server:
  port: 8080

spring:
  application:
    name: api-gateway

# Service URLs
app:
  services:
    user-service:
      url: ${User-Service-URL:http://localhost:8081}
    project-service:
      url: ${Project-Service-URL:http://localhost:8082}
    task-service:
      url: ${Task-Service-URL:http://localhost:8083}
    notification-service:
      url: ${Notification-Service-URL:http://localhost:8084}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.taskflow.api_gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: always
